# Generated by Django 3.2 on 2021-04-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('desc', models.TextField(max_length=1000, null=True)),
                ('inventory', models.IntegerField(blank=True, default=1, null=True)),
                ('show', models.BooleanField(default=False)),
                ('tag', models.CharField(max_length=20, null=True)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodscategory')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.BooleanField()),
                ('date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('cookie', models.CharField(max_length=20, null=True)),
                ('phoneNumber', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('address', models.CharField(max_length=100, null=True)),
                ('receiver', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('message', models.TextField(max_length=1000, null=True)),
                ('CustomerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
                ('GoodsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodsinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='img')),
                ('goodsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodsinfo')),
            ],
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='sellerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
