# Generated by Django 3.2 on 2021-04-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cag_name', models.CharField(max_length=30)),
                ('cag_css', models.CharField(max_length=20, null=True)),
                ('cag_img', models.ImageField(null=True, upload_to='cag')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('admin', models.BooleanField()),
                ('date', models.DateField(blank=True, null=True)),
                ('balance', models.DecimalField(decimal_places=5, default=0.0, max_digits=20)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('cookie', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Useraddr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=100, null=True)),
                ('goods_price', models.IntegerField(blank=True, default=0, null=True)),
                ('goods_desc', models.CharField(max_length=1000, null=True)),
                ('goods_inventory', models.IntegerField(blank=True, default=1, null=True)),
                ('goods_cag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodscategory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.ImageField(upload_to='goods')),
                ('goods_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goodsinfor')),
            ],
        ),
    ]
