# Generated by Django 3.2 on 2021-04-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_message_orderinfo_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
