# Generated by Django 3.2 on 2021-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_orderinfo_removal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='CustomerId',
            new_name='customerId',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='GoodsId',
            new_name='goodsId',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
