# Generated by Django 3.2 on 2021-04-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210417_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='sign',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
