# Generated by Django 3.2 on 2021-04-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210418_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='phoneNumber',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receiver',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
