# Generated by Django 3.2 on 2021-04-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210418_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='sign',
        ),
    ]
