# Generated by Django 3.2 on 2021-04-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_orderinfo_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='sign',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
