# Generated by Django 3.2 on 2021-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_orderinfo_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='remark',
            field=models.TextField(null=True),
        ),
    ]
