# Generated by Django 3.2 on 2021-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210419_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
