# Generated by Django 3.2 on 2021-04-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_payorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payorder',
            name='trade_no',
            field=models.CharField(max_length=64, null=True, verbose_name='流水号'),
        ),
    ]
