# Generated by Django 3.2 on 2021-05-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_payorder_trade_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
